### ISSUE TITLE
Template Engine

### ISSUE THREAD

**Issue by ahilles107** [superdesk/web-renderer#13]
We want to give easy to use and powerful tool for fetching content in WebPublisher templates. This for why we need context object.

# Proposal 
```updated: 23.07.2015 15:08```
#### Template

**getters:**
Get default data from context:
```twig 
{{ gimme.article.title}} - print current article title
{{ gimme.user.name }} - print current user name
```

Get single custom object:

```twig
{% gimme ‘article’ {param: 1}  %}
     {{ article.name }} 
{% endgimme %}
```

Get collection of objects:

Tag ```gimmelist``` have two required parameter and four optional:

 * (required) Name of variable available inside block: `article`
 * (required) Keword :code:`from` and type of requested Meta's in collection: `from articles`
 * (optional) Keword :code:`with` and parameters for Meta Loader ex.: `with {foo: 'bar', param1: 'value1'}`
 * (optional) Keword `if` and expresion used for results filtering
 * (optional) Number of first item used in pagination of list: `start=0`
 * (optional) Collection limit used in pagination of list: `limit=10`

required parameters:

```
    {% gimmelist article from articles %}
        {{ dump(article)}}
        {{ article.title }}
    {% endgimmelist %}
```

all parameters:

```twig

    {% gimmelist article from articles with {foo: 'bar', param1: 'value1'} if article.is_public start=0 limit=10 %}
        {{ dump(article)}}
        {{ article.title }}
    {% endgimmelist %}
```

**check if object is available**
```twig
{% if gimme.article is defined %}
    ...
{% endif %}
```

#### Backend

Context will be determined by listeners based on current route, it can be filled also from controller level.

Example:
```
<?php


/**
 * @Context("article", class="WebRendere:Article", options={"id" = "article_id"})
 * @Route("/article/{article_id}")
 */
public function showArticleAction(Article $article)
{
    // this will also work
    $context->set('article', $article);
}

```

#### Objects exposed for templators. 
Templator will not get access to internal entities or content repository objects - there will be special Meta class ```SWP/TemplateEngine/Meta```.

Every meta object will be define and documented with special yml configuration file. 

Example:
```yml
Article:
    properties:
        title:
            description: "Article title, max 160 characters, can't have any html tags"
            # optional custom getter
            getter: getArticle
        keywords:
            description: "Article keywords"
```

Based on this configuration, public properties will be added and filled with data from storage in ```SWP/TemplateEngine/Meta``` object available for templator under ```g.article```

**Comment by takeit** [comment]
what about configuring it using xml config file and not annotations (I mean Context annotations here)? I think we will be able to reuse the context object classes without relying on the coupled annotations since we will have it in a separate files (not in the classes itself). In my opinion, in this case abstracting it away from the code would make sense, what do you think about it ?

**Comment by ahilles107** [comment]
what would be pluses of using context config in seperate xml files? We should be able reuse context object anywhere annotations will be just one way to automatically fill context with needed objects. You will can still use methods like that:
```
$context->set('article', $article);
```

**Comment by takeit** [comment]
#### Fetching data from the context in Twig template

```twig
{{ g.get('articles', {param:1})) }}
```
 - function above will fetch articles by given parameters
 - `articles` can be replaced by a different value, e.g. `authors` - authors will be fetched by given parameters instead.

**Pros:**  
- one function to maintain (no need to create methods like `getArticles`,  `getAuthors` etc.) - documenting ease.

**Cons:**
- ?

**Comment by petrjasek** [comment]
not sure if those `Meta` classes should have methods, imo it would be better to keep there only data and provide template blocks/functions. so there would be `g.article.images` list and block:
```
{{ image src=g.article.images.0 width=300 height=200 }}
<img {{ g.image.params }}>
{{ /image }}
```
otherwise it's kind of complicated to use that - you have to store the func result somewhere and check it returned something etc.

**Comment by petrjasek** [comment]
also not sure about this change method, imo it would be better to use blocks again:
```
{{ article slugline="something" }} here you have the article context {{ /article }} and you're back where you were
```
this way you can in theory cache that block based on article updated time and in case you can't find it you just don't display it so it's more like component

if article change doesn't work there is no way to continue rendering after..

**Comment by takeit** [comment]
```twig
{% get ‘article’ {param: 1}  %}
     {{ g.name }} 
{% endget %}
```

**Comment by ahilles107** [comment]
ok, so to do not forget - i will add this in comment and then update proposal. 

Rafał comment (https://github.com/superdesk/web-renderer/issues/13#issuecomment-121896752) is our proposal for template side - fetching single item (different that one in context) and creating loops through collection of objects. 

We also decided to keep template "meta" objects configuration in yaml format seperate to entities. This same with phpcr configuration for documents.

Objects exposed for templators will be type of ```SWP/TemplateEngine/Meta``` and will be simple object with __get magic methods witch will expose only defined in configuration properties from storage objects (```documents```).

**Comment by petrjasek** [comment]
looks good. not sure about this meta class thing with magic methods, i would rather keep it simple, more like in [newscoop](https://github.com/sourcefabric/Newscoop/blob/master/newscoop/library/Newscoop/View/ArticleView.php) but as long as it's simple to create those meta classes without having an entity it should be fine. concerns for usage of those are - simple json dumping to javascript and using this in unittests.
so can you `json_encode()` metaclass?

**Comment by ahilles107** [comment]
We should be able to json_encode metaclass. And this metaclass will can be filled with any data, by default automatically it will look for public properties and getters in provided object, but still we should be abble to fill it in other ways.

**Comment by petrjasek** [comment]
should be fine then

**Comment by MiczFlor** [comment]
Hm... it reads like PHP 1.0 :) meaning: is this a template language for front end designers or is this a programming language?

**Comment by ahilles107** [comment]
Template section is for templators, rest is for developers, and it's realy close to that what we have in Newscoop templates (blocks, and lists).

**Comment by MiczFlor** [comment]
Hi guys, just want to suggest a few things in general, not sure about the specifics. My brain isn't good enough for this. But what do you think about this:

1. wording of variables should be the same as in the Superdesk Content API. If it is called "item" in Superdesk, it should not be called "article" in the web publishing template. This I say from experience. Horrible experience. Painful. You don't want that. Please check in with the Content API guys.

2. there should be one way of doing something, not many. As much as I like Larry Wall's post modern take on programming ( http://crossfade.walkerart.org/radioqualia/index.html ), if you use gimme, use it everywhere. If you use g. use it everywhere. Do not use both. 

3. before anything goes into commits, check the name spaces / variable wording with at least one native speaker and at least one newsroom magician. In this case, the language is a tool and means something. We can not accept inaccuracy and sloppy wording.

**Comment by ahilles107** [comment]
Hey @MiczFlor,

1. Main question if people working with templates will need to know that behind web publisher is Superdesk Content API, and if inside Superdesk Web Publisher they will still work with items or maybe with final web product - articles/pages ? Content API naming is designed for developer who will build app on this - not exactly some frontend guy who knows some jQuery and html and have contact do designer. 

2. There will be one naming - probably gimme ;)

3. We will need find newsroom magician, and include him in our pull requests review workflow.

**Comment by ljubar** [comment]
Currently in lists we have: length, ordering, ignoring context levels, constraints. Having less than this wouldn't be good. 
How this listing will look like in Web publisher? For example some article list rich with options currently looks like this
{{ list_articles length="10" columns="5" ignore_issue="true" ignore_section="true" order="byPopularity desc" constraints="type is news author is $escapedAuthor publish_date greater $threeDaysAgo" }}
how it translates to new system?

**Comment by ahilles107** [comment]
```twig 
{% gimmelist article in articles|length(10)|order('popularity, 'desc') with {
    type: 'news',
    autor: escapedAuthor, 
    publish_date: '>= '~threeDaysAgo
} %}
```

**Comment by ahilles107** [comment]
collumns and ignoring context stuff - not sure if we will have features like that
